[package]
authors = ["Connor Slade <connor@connorcode.com>"]
edition = "2018"
name = "scout_schedule"
version = "0.1.0"

[dependencies]
afire = {version = "0.1.6", features = ["logging"]}
simple_config_parser = "0.1.6"
serde_json = "1.0.68"
sha2 = "0.9.8"
