[package]
authors = ["Connor Slade <connor@connorcode.com>"]
edition = "2018"
name = "scout_schedule"
version = "1.0.1"

[dependencies]
afire = {version = "0.2.0", features = ["logging"]}
simple_config_parser = "1.0.0"
serde_json = "1.0.68"
sha2 = "0.9.8"
